### ISSUE TITLE
Multiple baselayers gets loaded in Leaflet

### ISSUE THREAD

**Issue by sabas** [cyberhobo/wp-geo-mashup#12]
I see that the two baselayers are active at load, I suspect the problem is this line
https://github.com/cyberhobo/wp-geo-mashup/blob/e8084214384f24b1ff00d67d9ce8057dfe4a4b8c/js/mxn/mxn.leaflet.core.js#L313

When there are multiple tilelayers and a layer control, addLayer (or addTo) should be called only on the layer one wants active at load time (because the others are activated when clicking on the radio button.

**Comment by cyberhobo** [comment]
Fixed by #13.
